### ISSUE TITLE
RS/TR integration crash

### ISSUE THREAD

**Issue by Slyklaw** [FTBTeam/FTB-Sky-Odyssey#3]
RS Crafter on TR Electric Furnace.

> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
> 	at java.util.Objects.requireNonNull(Unknown Source)
> 	at java.util.Optional.<init>(Unknown Source)
> 	at java.util.Optional.of(Unknown Source)
> 	at java.util.stream.FindOps$FindSink$OfRef.get(Unknown Source)
> 	at java.util.stream.FindOps$FindSink$OfRef.get(Unknown Source)
> 	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
> 	at reborncore.common.powerSystem.TilePowerAcceptor.getCapability(TilePowerAcceptor.java:294)
> 	at com.raoulvdberge.refinedstorage.util.WorldUtils.getItemHandler(WorldUtils.java:37)
> 	at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeCrafter.getConnectedInventory(NetworkNodeCrafter.java:285)
> 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateProcessing(CraftingTask.java:703)
> 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:882)
> 	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:172)
> 	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:211)

**Comment by Slyklaw** [comment]
Not actually refined storage related. Even just a hopper outputting to the machine will crash.
