### ISSUE TITLE
Unable to open this modpack at all, launcher will not load Minecraft.

### ISSUE THREAD

**Issue by Kamelgirl** [FTBTeam/FTB-Sky-Odyssey#427]
* **Modpack Version**: FTB Sky Odyssey 1.1.0 (Minecraft Launcher 1.6.91)

* **Issue**: Essentially it will open a launcher when i click on "Play" on the twitch app and then when I click "Play" on the minecraft launcher it will start loading and then never opens a minecraft window, it simply displays an error message(?) every time I click it.

* **Link to Log or Crash File Paste**: 

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

* **Is it Repeatable?**: Every time I try to load it the same thing happens.

* **Mod/s Affected**: I have no idea what is causing it.

If you have a fix please let me know I loved this modpack in a playthrough I watched and would love to play for myself!

**Comment by Kamelgirl** [comment]
I tried this with another modpack and it also didn't work, I'm assuming that means the problem is to do with my laptop / my end, so if you know what to do to fix it then also very much appreciated!
