### ISSUE TITLE
Crash when opening game

### ISSUE THREAD

**Issue by Greeneen** [FTBTeam/FTB-Sky-Odyssey#464]
* **Modpack Version**: 1.1.0

* **Issue**: Game crashes as it opens itself

* **Link to Log or Crash File Paste**: Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: unknown

* **Known Fix**: unknown

**Comment by SuplierZWTF** [comment]
means your pc sux.

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> means your pc sux.

Can this problem be solved by allowing more RAM ?

**Comment by Greeneen** [comment]
> > means your pc sux.
> 
> Can this problem be solved by allowing more RAM ?

No, it isn't possible. The game crashes before I can allocate more RAM. I did forget to mention that I am using the Twitch app, since there's nothing else on curseforge that I can use.

**Comment by MrKinau** [comment]
The problem is that you use a too new version of java (I think 9+) You have to install java 8 and use this for running minecraft

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> The problem is that you use a too new version of java (I think 9+) You have to install java 8 and use this for running minecraft

I searched on my pc and java is on "version 8 update 201 (build 1.8.0_201-b09)"
PS: I have the same problem

btw, you can allocate more RAM by the twitch app Greeneen. And, when the crash first occurred, did you have A LOT of RF in a flux network ? I crashed just after placing 64 petrified fuel generator with 50k rf/tick each and getting all of theses in a flux network.

**Comment by MrKinau** [comment]
Well, your MC definitely startsup with Java 9+ otherwise I can't explain this crashlog. Maybe you have installed multiple instances of java (if you don't need uninstall all other java instances except for the 1.8 one or just reinstall java completely. Otherwise you can set your Java home (maybe in Twitch launcher idk) or in the JAVA_HOME environmet variable in your os to the java 1.8 installation)

**Comment by Thisisnotanappropriatepseudo** [comment]
Just saw someone answering to this question, I'll see if this works for me :

#435 (comment)

**Comment by Thisisnotanappropriatepseudo** [comment]
I love you MrKinau :3. I tried for 30 mins to understand how mcedit works, but it WORKS, Thanks ALOT !

**Comment by Thisisnotanappropriatepseudo** [comment]
Hi, thanks ALOT because my save works now, but I lost all of the things I had in the transmutation tablet. As I am in the map " The Middle", I could have taken the tome of knowledge, but it doesn't work. Do you have any idea to get back my transmutations ?
