### ISSUE TITLE
crash after loading screen is done (pls help) i was doing modded mc series on yt

### ISSUE THREAD

**Issue by FurkanOzaydinAp** [FTBTeam/FTB-Sky-Odyssey#492]
* **Modpack Version**: 1.10

* **Issue**: i cant get my world and it gets a crash when its done loading

* **Link to Log or Crash File Paste**: -- Head --
Thread: Client thread
Stacktrace:
	at crazypants.enderio.base.power.forge.item.InternalPoweredItemCap.<init>(InternalPoweredItemCap.java:15)
	at crazypants.enderio.powertools.machine.capbank.BlockItemCapBank.initCapabilities(BlockItemCapBank.java:22)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1215)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)
	at portablejim.bbw.core.WandWorker.getEquivalentItemStack(WandWorker.java:106)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:91)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2047_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['beastboy123g'/232, l='MpServer', x=-31.82, y=99.00, z=-26.96]]
	Chunk stats: MultiplayerChunkCache: 44, 44
	Level seed: 0
	Level generator: ID 07 - void, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,96,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1817440 game time, 6001 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityItemFrame['entity.ItemFrame.name'/212, l='MpServer', x=-31.50, y=100.50, z=5.97], EntityPlayerSP['beastboy123g'/232, l='MpServer', x=-31.82, y=99.00, z=-26.96]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

* **Is it Repeatable?**: it keeps giving me same crash over and over when i try to load the map

* **Mod/s Affected**: no, no mods got added or deleted

* **Known Fix**: thats what i wanna know

**Comment by MrKinau** [comment]
This happens because you are currently looking at a capacitor bank. This is very buggy in this modpack. Try avoiding capacitor banks. A guide to join your world without crashes can be found here: https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/435#issuecomment-531671719
