### ISSUE TITLE
Unable to buy loot crates

### ISSUE THREAD

**Issue by BDMCGaming** [FTBTeam/FTB-Sky-Odyssey#570]
* **Modpack Version**: 1.3.0

* **Issue**: I can't buy loot crates no matter how many times I try despite having more than enough money. A loot crate costs 1,000 coins and I have over 

* **Link to Log or Crash File Paste**: It doesn't crash.

* **Is it Repeatable?**: Yes. I go to the shop in a world and try to buy a loot crate, and it doesn't work.

**Comment by TH3GOD88** [comment]
Having the same problem. Even on a server. It throws an error when trying to buy them.

[19:43:48] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at com.feed_the_beast.mods.money.shop.ShopEntry.isUnlocked(ShopEntry.java:120) ~[ShopEntry.class:?]
        at com.feed_the_beast.mods.money.net.MessageBuy.onMessage(MessageBuy.java:71) ~[MessageBuy.class:?]
        at com.feed_the_beast.ftblib.lib.net.MessageToServerHandler.lambda$onMessage$0(MessageToServerHandler.java:27) ~[MessageToServerHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
