### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by nateheron** [FTBTeam/FTB-Sky-Odyssey#82]
I know this is probably really dumb but i dont know code. So what does this mean???

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[20:06:05] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:06:05] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by JandHCo** [comment]
Make sure you're running on java 8. This pack is not compatible with anything later.
If you dont know what version you're on type "java -version" in command prompt or in terminal if you're on MacOS.

**Comment by nateheron** [comment]
<img width="374" alt="Screen Shot 2019-03-20 at 5 56 25 AM" src="https://user-images.githubusercontent.com/48396331/54685826-01c9c280-4ad5-11e9-9872-57023c1e6aa4.png">
this is the current version of my java

**Comment by Cloudhunter** [comment]
This is odd. How are you running the server - have you made sure to use the sh provided by FTB which will download all required libraries and the Minecraft Server jar?

**Comment by GenesisXBD** [comment]
Just out of curiosity how much ram do you have allocated?

**Comment by nateheron** [comment]
All I have done is just download the pack of the twitch launcher like I would any other pack. Many other packs work just not this one. 


I would tell you how much ram I have allocated but I am not sure how to do that. Im using a mac if that helps at all.

**Comment by JandHCo** [comment]
Press CMD+, 
This should open a settings page. Go to “Minecraft” and then scroll down to your RAM allocation. If you have 16GB I would suggest only going up to 8GB of allocated RAM.

**Comment by nateheron** [comment]
I am unable to even load the minecraft loading screen. It is completely fine in the launcher, but once I try and click to open actual minecraft nothing pops up and the error message comes up in the minecraft launcher. I tried using activity moniter and no jump in memory or cpu usage happens when I try to launch minecraft

**Comment by nateheron** [comment]
Update. I tried going back a version in forge and now it is working so thanks everyone for the help!!
